version: '3'
services:
  demo_face_aging:
    build: .
    container_name: demo_face_aging
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/home/project
    networks:
      static-network:
        ipv4_address: 172.2.0.6
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.2.0.0/16
          #docker-compose v3+ do not use ip_range
          # ip_range: 192.168.0.1/24
